[package]
name = "charybdis"
version = "0.1.0"
authors = ["ast-ral <ast.hyphen.ral@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.8"
